name: Build project

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo add-apt-repository --yes ppa:kicad/kicad-8.0-releases
        sudo apt update
        sudo apt install --install-recommends kicad
        sudo apt install xsltproc

    - name: Run check
      run: make drc

    - name: Run build
      run: make build

    - name: Release
      uses: softprops/action-gh-release@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          hardware/build/*.zip
          hardware/build/*.pos.csv
          hardware/build/*.bom.csv
          hardware/build/*.bom.xml
